# Generated by Django 5.2.8 on 2025-11-21 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('kikuyu', 'Kikuyu'), ('english', 'English'), ('swahili', 'Swahili')], default='kikuyu', max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='vocab_audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocab_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_vocabs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='vocab.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vocab.vocab')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
