# Generated by Django 5.2.8 on 2025-11-24 08:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Noun', 'Verb')", max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version (auto-generated)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon for UI display', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('practiced', 'Practiced'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Learning Progress',
                'verbose_name_plural': 'Learning Progress',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vocab',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vocabulary Entry', 'verbose_name_plural': 'Vocabulary Entries'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for review by moderators'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='vocab',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level for learners', max_length=20),
        ),
        migrations.AddField(
            model_name='vocab',
            name='example_translation',
            field=models.TextField(blank=True, help_text='English translation of example sentence'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes, context, or cultural info'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='pronunciation_guide',
            field=models.CharField(blank=True, help_text="Written pronunciation guide (e.g., 'moo-n-doo')", max_length=200),
        ),
        migrations.AddField(
            model_name='vocab',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin notes on why entry was rejected'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When admin reviewed this entry', null=True),
        ),
        migrations.AddField(
            model_name='vocab',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved/rejected this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vocabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vocab',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], db_index=True, default='pending', help_text='Approval status (pending/approved/rejected)', max_length=20),
        ),
        migrations.AddField(
            model_name='vocab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification time'),
        ),
        migrations.AddField(
            model_name='vocab',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this word was viewed'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vocab',
            field=models.ForeignKey(help_text='The vocab entry this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vocab.vocab'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio pronunciation (MP3, WAV, OGG, M4A)', null=True, upload_to='vocab_audio/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this entry was created'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='example_sentence',
            field=models.TextField(blank=True, help_text='Example sentence using this word (in native language)'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who favorited this word', related_name='favorite_vocabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='image',
            field=models.ImageField(blank=True, help_text='Visual context (optional)', null=True, upload_to='vocab_images/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='language',
            field=models.CharField(choices=[('kikuyu', 'Kikuyu'), ('english', 'English'), ('swahili', 'Swahili')], db_index=True, default='kikuyu', max_length=20),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Contextual tags (food, family, travel, etc.)', related_name='vocab_entries', to='vocab.tag'),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='translation',
            field=models.CharField(db_index=True, help_text='English translation', max_length=100),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='user',
            field=models.ForeignKey(help_text='User who contributed this word', on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='word',
            field=models.CharField(db_index=True, help_text='The word in its native language', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vocab',
            unique_together={('word', 'language')},
        ),
        migrations.AddField(
            model_name='vocab',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (Noun, Verb, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocab_entries', to='vocab.category'),
        ),
        migrations.AddIndex(
            model_name='vocab',
            index=models.Index(fields=['status', 'language'], name='vocab_vocab_status_354be3_idx'),
        ),
        migrations.AddIndex(
            model_name='vocab',
            index=models.Index(fields=['-created_at'], name='vocab_vocab_created_2e3375_idx'),
        ),
        migrations.AddIndex(
            model_name='vocab',
            index=models.Index(fields=['word', 'translation'], name='vocab_vocab_word_cd0738_idx'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='vocab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='vocab.vocab'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('user', 'vocab'), name='unique_user_vocabulary'),
        ),
    ]
